#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Instituto de Investigaciones Agropecuarias (INIA), Chile
"""
Orthomosaic Tile Embedding CLI
===============================

Computes ResNet50 (or other backbone) embeddings from orthomosaic tiles
generated by tile_orthomosaic.py, then applies dimensionality reduction
(UMAP, PCA, t-SNE) and creates interactive visualizations.

Relationship to tile_orthomosaic.py:
    tile_orthomosaic.py splits a large orthomosaic GeoTIFF into 1024x1024
    JPEG tiles and produces a tile_manifest.csv with spatial metadata.
    This script takes those tiles as input, computes deep feature embeddings,
    and visualizes the embedding space colored by spatial position, row,
    or valid pixel fraction.

Usage:
    python scripts/05_domain_shift/embed_ortho_tiles.py \\
        --tiles /path/to/ortho_tiles_1024/ \\
        --output /path/to/embeddings_output/ \\
        --model resnet50 --batch-size 32 --device cuda:0

    # Quick test with subset
    python scripts/05_domain_shift/embed_ortho_tiles.py \\
        --tiles /path/to/ortho_tiles_1024/ \\
        --max-samples 200 --skip-tsne

Output:
    - embeddings.npz: Raw embeddings + metadata arrays
    - embeddings_reduced.csv: Reduced coordinates with tile metadata
    - embedding_summary.json: Configuration and statistics
    - umap_by_grid_zone.html: UMAP colored by spatial zone (3x3 grid)
    - umap_by_row.html: UMAP colored by row index (N-S gradient)
    - umap_by_valid_frac.html: UMAP colored by valid pixel fraction
    - pca_by_grid_zone.html: PCA colored by spatial zone
"""

import argparse
import json
import sys
import warnings
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from PIL import Image

# Add this script's folder to path so we can import embedding_backbone.py
sys.path.insert(0, str(Path(__file__).resolve().parent))

import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

# Import reusable components from the existing embeddings module
from embedding_backbone import (
    FeatureExtractor,
    extract_embeddings,
    reduce_dimensions,
)

# Suppress warnings for cleaner output
warnings.filterwarnings("ignore")


# ============================================================================
# TILE DATASET
# ============================================================================

class TileDataset(Dataset):
    """
    Dataset for loading orthomosaic tiles with optional manifest metadata.

    Scans a directory for .jpg tiles, loads the tile_manifest.csv if available,
    and attaches spatial metadata (row, col, georeferenced bounds, valid pixel
    fraction) to each tile.
    """

    def __init__(
        self,
        tiles_dir: str,
        manifest_path: Optional[str] = None,
        transform: Optional[transforms.Compose] = None,
        max_samples: int = 0,
    ):
        self.tiles_dir = Path(tiles_dir)
        self.transform = transform

        # Find all JPEG tiles
        extensions = {".jpg", ".jpeg", ".JPG", ".JPEG"}
        self.image_paths = []
        for ext in extensions:
            self.image_paths.extend(list(self.tiles_dir.glob(f"*{ext}")))
        self.image_paths.sort()

        # Limit samples if requested (0 = no limit)
        if max_samples > 0 and len(self.image_paths) > max_samples:
            self.image_paths = self.image_paths[:max_samples]

        # Load manifest if available
        self.manifest_df = None
        self._load_manifest(manifest_path)

        # Build metadata for each tile
        self.metadata = self._build_metadata()

        print(f"  Tiles found: {len(self.image_paths)}")
        if self.manifest_df is not None:
            print(f"  Manifest loaded: {len(self.manifest_df)} entries")
            matched = sum(1 for m in self.metadata if m.get("row") is not None)
            print(f"  Tiles matched to manifest: {matched}/{len(self.image_paths)}")
        else:
            print("  Manifest: not found (using filename-only metadata)")

    def _load_manifest(self, manifest_path: Optional[str]):
        """Load tile_manifest.csv with spatial metadata."""
        if manifest_path is not None:
            mp = Path(manifest_path)
        else:
            # Default: look inside tiles directory
            mp = self.tiles_dir / "tile_manifest.csv"

        if mp.exists():
            try:
                self.manifest_df = pd.read_csv(mp)
                # Ensure the filename column exists
                if "filename" not in self.manifest_df.columns:
                    # Try common alternatives
                    for col in ["tile_filename", "file", "name"]:
                        if col in self.manifest_df.columns:
                            self.manifest_df = self.manifest_df.rename(
                                columns={col: "filename"}
                            )
                            break
                if "filename" not in self.manifest_df.columns:
                    print(
                        f"  WARNING: Manifest at {mp} has no 'filename' column. "
                        f"Columns: {list(self.manifest_df.columns)}"
                    )
                    self.manifest_df = None
            except Exception as e:
                print(f"  WARNING: Could not read manifest {mp}: {e}")
                self.manifest_df = None
        else:
            if manifest_path is not None:
                print(f"  WARNING: Manifest not found at {manifest_path}")

    def _build_metadata(self) -> List[Dict]:
        """Build metadata list, merging manifest data where available."""
        metadata = []

        # Create a lookup from manifest if available
        manifest_lookup = {}
        if self.manifest_df is not None and "filename" in self.manifest_df.columns:
            for _, row in self.manifest_df.iterrows():
                manifest_lookup[row["filename"]] = row.to_dict()

        for path in self.image_paths:
            fname = path.name
            entry = {"filename": fname, "full_path": str(path)}

            if fname in manifest_lookup:
                mrow = manifest_lookup[fname]
                # Standard manifest columns from tile_orthomosaic.py
                for col in [
                    "row", "col", "x_min", "y_min", "x_max", "y_max", "frac_valid"
                ]:
                    entry[col] = mrow.get(col, None)
            else:
                # Try to parse row/col from filename pattern: tile_RRR_CCC.jpg
                parts = fname.replace(".jpg", "").replace(".jpeg", "").split("_")
                try:
                    # Attempt numeric parsing for patterns like tile_003_012.jpg
                    nums = [int(p) for p in parts if p.isdigit()]
                    if len(nums) >= 2:
                        entry["row"] = nums[0]
                        entry["col"] = nums[1]
                    else:
                        entry["row"] = None
                        entry["col"] = None
                except (ValueError, IndexError):
                    entry["row"] = None
                    entry["col"] = None

                entry["x_min"] = None
                entry["y_min"] = None
                entry["x_max"] = None
                entry["y_max"] = None
                entry["frac_valid"] = None

            metadata.append(entry)

        return metadata

    def __len__(self) -> int:
        return len(self.image_paths)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, int]:
        img_path = self.image_paths[idx]

        try:
            image = Image.open(img_path).convert("RGB")
            if self.transform:
                image = self.transform(image)
            return image, idx
        except Exception as e:
            print(f"  Error loading {img_path}: {e}")
            # Return a blank tensor on error
            return torch.zeros(3, 224, 224), idx


# ============================================================================
# GRID ZONE COMPUTATION
# ============================================================================

def compute_grid_zone(
    row: int, col: int, n_rows: int, n_cols: int, grid_size: int = 3
) -> str:
    """
    Assign a tile to a spatial grid zone based on its row/col position.

    Divides the orthomosaic into a grid_size x grid_size grid and returns
    a human-readable zone label (e.g., "top-left", "center", "bot-right").

    Args:
        row: Tile row index
        col: Tile column index
        n_rows: Total number of rows in the tile grid
        n_cols: Total number of columns in the tile grid
        grid_size: Number of divisions per axis (default 3 for 3x3 = 9 zones)

    Returns:
        Zone label string
    """
    zone_labels = [
        ["top-left", "top-center", "top-right"],
        ["mid-left", "center", "mid-right"],
        ["bot-left", "bot-center", "bot-right"],
    ]
    r = min(int(row / n_rows * grid_size), grid_size - 1)
    c = min(int(col / n_cols * grid_size), grid_size - 1)
    return zone_labels[r][c]


# ============================================================================
# VISUALIZATION (adapted for tile metadata)
# ============================================================================

def create_tile_visualization(
    df: pd.DataFrame,
    x_col: str,
    y_col: str,
    color_col: str,
    title: str,
    output_path: str,
    continuous_color: bool = False,
):
    """
    Create an interactive scatter plot for tile embeddings.

    Similar to create_visualization() in generate_embeddings.py but uses
    tile-specific hover columns instead of the hardcoded location/source_type.

    Args:
        df: DataFrame with coordinates and tile metadata
        x_col, y_col: Column names for 2D coordinates
        color_col: Column to use for coloring points
        title: Plot title
        output_path: Output HTML file path
        continuous_color: If True, use continuous color scale (for numeric cols)
    """
    import plotly.express as px

    # Build hover data from available columns
    hover_cols = ["filename"]
    for col in ["row", "col", "grid_zone", "frac_valid"]:
        if col in df.columns and col != color_col:
            hover_cols.append(col)

    if continuous_color:
        fig = px.scatter(
            df,
            x=x_col,
            y=y_col,
            color=color_col,
            hover_data=hover_cols,
            title=title,
            opacity=0.7,
            color_continuous_scale="Viridis",
        )
    else:
        fig = px.scatter(
            df,
            x=x_col,
            y=y_col,
            color=color_col,
            hover_data=hover_cols,
            title=title,
            opacity=0.7,
        )

    fig.update_traces(marker=dict(size=5))
    fig.update_layout(
        template="plotly_white",
        width=1200,
        height=800,
        legend=dict(yanchor="top", y=0.99, xanchor="left", x=1.02),
    )

    fig.write_html(output_path)
    print(f"    Saved: {output_path}")

    # Try to save static PNG as well
    png_path = output_path.replace(".html", ".png")
    try:
        fig.write_image(png_path, scale=2)
        print(f"    Saved: {png_path}")
    except Exception:
        pass  # kaleido not installed; skip silently

    return fig


# ============================================================================
# MAIN CLI
# ============================================================================

def parse_args():
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Compute ResNet50 embeddings from orthomosaic tiles and visualize with UMAP/PCA.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""\
Examples:
  # Basic usage (auto-detect manifest and output dir)
  python scripts/05_domain_shift/embed_ortho_tiles.py --tiles /path/to/ortho_tiles_1024/

  # Full options
  python scripts/05_domain_shift/embed_ortho_tiles.py \\
      --tiles /path/to/ortho_tiles_1024/ \\
      --manifest /path/to/tile_manifest.csv \\
      --output /path/to/embeddings_output/ \\
      --model resnet50 --batch-size 32 --device cuda:0

  # Quick test with 200 tiles, skip t-SNE
  python scripts/05_domain_shift/embed_ortho_tiles.py \\
      --tiles /path/to/ortho_tiles_1024/ \\
      --max-samples 200 --skip-tsne
""",
    )
    parser.add_argument(
        "--tiles",
        required=True,
        help="Path to directory containing JPEG tile images",
    )
    parser.add_argument(
        "--manifest",
        default=None,
        help="Path to tile_manifest.csv (default: looks inside --tiles dir)",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output directory (default: <tiles_dir>/../ortho_embeddings/)",
    )
    parser.add_argument(
        "--model",
        default="resnet50",
        choices=["resnet50", "efficientnet_b0", "efficientnet_b2"],
        help="Backbone model for feature extraction (default: resnet50)",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=32,
        help="Batch size for inference (default: 32)",
    )
    parser.add_argument(
        "--max-samples",
        type=int,
        default=0,
        help="Limit number of tiles to process. 0 = all (default: 0)",
    )
    parser.add_argument(
        "--device",
        default=None,
        help="Device for inference, e.g. cuda:0 or cpu (default: auto-detect)",
    )
    parser.add_argument(
        "--skip-tsne",
        action="store_true",
        help="Skip t-SNE computation (saves time for large datasets)",
    )
    return parser.parse_args()


def main():
    """Main entry point for the orthomosaic tile embedding CLI."""
    args = parse_args()

    # =========================================================================
    # Banner
    # =========================================================================
    print("=" * 70)
    print("ORTHOMOSAIC TILE EMBEDDING PIPELINE")
    print("=" * 70)
    print(f"  Date     : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"  Tiles    : {args.tiles}")
    print(f"  Model    : {args.model}")
    print(f"  Batch    : {args.batch_size}")
    max_label = "all" if args.max_samples == 0 else str(args.max_samples)
    print(f"  Max tiles: {max_label}")
    print(f"  t-SNE    : {'skip' if args.skip_tsne else 'compute'}")

    # Resolve device
    if args.device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"
    else:
        device = args.device
    print(f"  Device   : {device}")

    # Resolve output directory
    tiles_dir = Path(args.tiles).resolve()
    if not tiles_dir.is_dir():
        print(f"\nERROR: Tiles directory does not exist: {tiles_dir}")
        sys.exit(1)

    if args.output is not None:
        output_dir = Path(args.output).resolve()
    else:
        output_dir = tiles_dir.parent / "ortho_embeddings"

    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"  Output   : {output_dir}")
    print("=" * 70)
    print()

    # =========================================================================
    # [1/4] Load tiles
    # =========================================================================
    print("-" * 70)
    print("[1/4] Load tiles")
    print("-" * 70)

    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225],
        ),
    ])

    dataset = TileDataset(
        tiles_dir=str(tiles_dir),
        manifest_path=args.manifest,
        transform=transform,
        max_samples=args.max_samples,
    )

    if len(dataset) == 0:
        print("\nERROR: No tile images found in the specified directory.")
        sys.exit(1)

    print()

    # =========================================================================
    # [2/4] Extract embeddings
    # =========================================================================
    print("-" * 70)
    print("[2/4] Extract embeddings")
    print("-" * 70)

    print(f"  Initializing {args.model} model...")
    model = FeatureExtractor(args.model)
    print(f"  Embedding dimension: {model.embedding_dim}")

    embeddings = extract_embeddings(
        dataset=dataset,
        model=model,
        batch_size=args.batch_size,
        num_workers=4,
        device=device,
    )
    print(f"  Embeddings shape: {embeddings.shape}")

    if embeddings.ndim != 2:
        print(f"ERROR: Embeddings must be 2D, got shape {embeddings.shape}")
        sys.exit(1)

    print()

    # =========================================================================
    # [3/4] Reduce dimensions
    # =========================================================================
    print("-" * 70)
    print("[3/4] Reduce dimensions")
    print("-" * 70)

    # UMAP 2D
    print("\n  [a] UMAP 2D...")
    try:
        umap_2d = reduce_dimensions(embeddings, method="umap", n_components=2)
    except ImportError:
        print(
            "\n  ERROR: umap-learn is not installed."
            "\n  Install it with: pip install umap-learn"
            "\n  or: conda install -c conda-forge umap-learn"
        )
        sys.exit(1)

    # PCA 2D
    print("\n  [b] PCA 2D...")
    pca_2d = reduce_dimensions(embeddings, method="pca", n_components=2)

    # t-SNE 2D (optional)
    tsne_2d = None
    if not args.skip_tsne:
        print("\n  [c] t-SNE 2D...")
        tsne_2d = reduce_dimensions(embeddings, method="tsne", n_components=2)
    else:
        print("\n  [c] t-SNE 2D... SKIPPED (--skip-tsne)")

    print()

    # =========================================================================
    # Build DataFrame
    # =========================================================================
    print("-" * 70)
    print("  Building results DataFrame...")
    print("-" * 70)

    df = pd.DataFrame(dataset.metadata)

    # Add reduced coordinates
    df["umap_x"] = umap_2d[:, 0]
    df["umap_y"] = umap_2d[:, 1]
    df["pca_x"] = pca_2d[:, 0]
    df["pca_y"] = pca_2d[:, 1]

    if tsne_2d is not None:
        df["tsne_x"] = tsne_2d[:, 0]
        df["tsne_y"] = tsne_2d[:, 1]

    # Compute grid_zone for tiles that have row/col metadata
    has_rowcol = df["row"].notna() & df["col"].notna()
    if has_rowcol.any():
        n_rows = int(df.loc[has_rowcol, "row"].max()) + 1
        n_cols = int(df.loc[has_rowcol, "col"].max()) + 1

        df["grid_zone"] = "unknown"
        for idx in df.index[has_rowcol]:
            df.at[idx, "grid_zone"] = compute_grid_zone(
                int(df.at[idx, "row"]),
                int(df.at[idx, "col"]),
                n_rows,
                n_cols,
            )

        # Convert row to string for categorical coloring
        df["row_str"] = df["row"].apply(
            lambda v: f"row_{int(v):03d}" if pd.notna(v) else "unknown"
        )
    else:
        df["grid_zone"] = "unknown"
        df["row_str"] = "unknown"

    # Ensure frac_valid is numeric
    if "frac_valid" in df.columns:
        df["frac_valid"] = pd.to_numeric(df["frac_valid"], errors="coerce")

    print(f"  Total tiles: {len(df)}")
    if has_rowcol.any():
        print(f"  Grid size: {n_rows} rows x {n_cols} cols")
        print(f"  Grid zones:")
        for zone, count in df["grid_zone"].value_counts().sort_index().items():
            print(f"    {zone}: {count}")
    print()

    # =========================================================================
    # [4/4] Create visualizations
    # =========================================================================
    print("-" * 70)
    print("[4/4] Create visualizations")
    print("-" * 70)

    # Check for plotly
    try:
        import plotly.express  # noqa: F401
    except ImportError:
        print(
            "\n  ERROR: plotly is not installed."
            "\n  Install it with: pip install plotly"
        )
        sys.exit(1)

    files_created = []

    # 1. UMAP by grid zone
    print("\n  [a] UMAP by grid zone...")
    fpath = str(output_dir / "umap_by_grid_zone.html")
    create_tile_visualization(
        df,
        x_col="umap_x",
        y_col="umap_y",
        color_col="grid_zone",
        title="UMAP - Tile Embeddings by Grid Zone (3x3)",
        output_path=fpath,
    )
    files_created.append("umap_by_grid_zone.html")

    # 2. UMAP by row
    print("\n  [b] UMAP by row index...")
    fpath = str(output_dir / "umap_by_row.html")
    create_tile_visualization(
        df,
        x_col="umap_x",
        y_col="umap_y",
        color_col="row_str",
        title="UMAP - Tile Embeddings by Row (N-S gradient)",
        output_path=fpath,
    )
    files_created.append("umap_by_row.html")

    # 3. UMAP by valid fraction (continuous color)
    if df["frac_valid"].notna().any():
        print("\n  [c] UMAP by valid pixel fraction...")
        fpath = str(output_dir / "umap_by_valid_frac.html")
        # Work on a copy that drops NaN frac_valid rows for this plot
        df_valid = df.dropna(subset=["frac_valid"]).copy()
        if len(df_valid) > 0:
            create_tile_visualization(
                df_valid,
                x_col="umap_x",
                y_col="umap_y",
                color_col="frac_valid",
                title="UMAP - Tile Embeddings by Valid Pixel Fraction",
                output_path=fpath,
                continuous_color=True,
            )
            files_created.append("umap_by_valid_frac.html")
        else:
            print("    Skipped: no valid frac_valid data")
    else:
        print("\n  [c] UMAP by valid fraction... Skipped (no frac_valid data)")

    # 4. PCA by grid zone
    print("\n  [d] PCA by grid zone...")
    fpath = str(output_dir / "pca_by_grid_zone.html")
    create_tile_visualization(
        df,
        x_col="pca_x",
        y_col="pca_y",
        color_col="grid_zone",
        title="PCA - Tile Embeddings by Grid Zone (3x3)",
        output_path=fpath,
    )
    files_created.append("pca_by_grid_zone.html")

    # 5. t-SNE by grid zone (if computed)
    if tsne_2d is not None:
        print("\n  [e] t-SNE by grid zone...")
        fpath = str(output_dir / "tsne_by_grid_zone.html")
        create_tile_visualization(
            df,
            x_col="tsne_x",
            y_col="tsne_y",
            color_col="grid_zone",
            title="t-SNE - Tile Embeddings by Grid Zone (3x3)",
            output_path=fpath,
        )
        files_created.append("tsne_by_grid_zone.html")

    print()

    # =========================================================================
    # Save outputs
    # =========================================================================
    print("-" * 70)
    print("  Saving outputs...")
    print("-" * 70)

    # 1. Raw embeddings (.npz)
    npz_path = output_dir / "embeddings.npz"

    # Build metadata array for downstream compatibility
    metadata_array = np.array([
        {
            'filename': m['filename'],
            'row': m.get('row'),
            'col': m.get('col'),
            'grid_zone': m.get('grid_zone', ''),
            'frac_valid': m.get('frac_valid', 1.0),
        }
        for m in dataset.metadata
    ], dtype=object)

    np.savez_compressed(
        npz_path,
        embeddings=embeddings,
        metadata=metadata_array,
        filenames=np.array([m["filename"] for m in dataset.metadata]),
        rows=np.array(
            [m.get("row", -1) if m.get("row") is not None else -1 for m in dataset.metadata],
            dtype=np.float32,
        ),
        cols=np.array(
            [m.get("col", -1) if m.get("col") is not None else -1 for m in dataset.metadata],
            dtype=np.float32,
        ),
    )
    print(f"  Saved: {npz_path}")
    files_created.append("embeddings.npz")

    # 2. Reduced embeddings CSV
    csv_path = output_dir / "embeddings_reduced.csv"
    # Drop full_path from CSV to keep it portable
    df_save = df.drop(columns=["full_path"], errors="ignore")
    df_save.to_csv(csv_path, index=False)
    print(f"  Saved: {csv_path}")
    files_created.append("embeddings_reduced.csv")

    # 3. Summary JSON
    summary = {
        "timestamp": datetime.now().isoformat(),
        "tiles_dir": str(tiles_dir),
        "output_dir": str(output_dir),
        "model": args.model,
        "device": device,
        "batch_size": args.batch_size,
        "n_tiles": len(df),
        "embedding_dim": int(embeddings.shape[1]),
        "max_samples": args.max_samples,
        "skip_tsne": args.skip_tsne,
        "reductions": ["umap_2d", "pca_2d"] + (["tsne_2d"] if tsne_2d is not None else []),
        "grid_zones": (
            df["grid_zone"].value_counts().to_dict()
            if has_rowcol.any()
            else {}
        ),
        "files_created": files_created,
    }

    # Add manifest info if available
    if dataset.manifest_df is not None:
        summary["manifest_path"] = str(
            Path(args.manifest).resolve() if args.manifest else tiles_dir / "tile_manifest.csv"
        )
        summary["manifest_rows"] = len(dataset.manifest_df)

    summary_path = output_dir / "embedding_summary.json"
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2)
    print(f"  Saved: {summary_path}")
    files_created.append("embedding_summary.json")

    print()

    # =========================================================================
    # Final summary
    # =========================================================================
    print("=" * 70)
    print("PIPELINE COMPLETED SUCCESSFULLY")
    print("=" * 70)
    print()
    print(f"  Tiles processed : {len(df)}")
    print(f"  Embedding dim   : {embeddings.shape[1]}")
    print(f"  Output directory : {output_dir}")
    print()
    print("  Files created:")
    for f in sorted(output_dir.glob("*")):
        size = f.stat().st_size / 1024
        unit = "KB"
        if size > 1024:
            size /= 1024
            unit = "MB"
        print(f"    {f.name}: {size:.1f} {unit}")
    print()


if __name__ == "__main__":
    main()
